### ISSUE TITLE
delete unnecessary warnings

### ISSUE THREAD

**Issue by ZoltanRacz** [ZoltanRacz/MomentMatching.jl#52]
perhaps make error catching as a feature that can be turned on/off through keyword

**Comment by gualtiazza** [comment]
At the moment I get the following warnings when loading the package:
┌ Warning: Changes 1: estimation now accepts vectors of starting guesses in onlyloc mode
└ @ MomentMatching ~/github/MomentMatching.jl/src/estimation.jl:20
┌ Warning: We need to check 
└ @ MomentMatching ~/github/MomentMatching.jl/src/estimation.jl:55
┌ Warning: error catching is off!!
└ @ MomentMatching ~/github/MomentMatching.jl/src/estimation.jl:485

the first I think can be eliminated, we are aware of that by now, the second relates to AuxiliaryParameters and at the moment I do not remember why we introduced it (but as it is now that can also be deleted)

The third comment is instead what you write in the original message in this issue, we should have a on/off option

**Comment by ZoltanRacz** [comment]
I agree, first two warnings are totally unnecessary. I will just delete all three warnings and create a new issue instead for the third one
