### ISSUE TITLE
Save local points in order of inputs

### ISSUE THREAD

**Issue by ZoltanRacz** [ZoltanRacz/MomentMatching.jl#87]
Instead of saving local points ordered from best point to worst, we should save them in the order of starting points serving as input.

Pro:
- The original order is informative: assuming first guesses were the best global points, the order of local points can help us decide if we should start locals from more global points
- When multiprocessing, probably it will be optimal to do estimations in smaller batches. Assembling these into one estimation result is more straightforward without reordering all the time.

Con:
- for some outputs the ordered points are needed. So if we don't order while saving, either we save the ordering or need to order every time when running fsanity or other stuff
- would need to change a few functions that assumes first point is best point.

**Comment by gualtiazza** [comment]
Added a new element in EstimationResult structure that contains the original order of the local points. This way we just need to write a new plot to see to which global points the local correspond instead of changing all the functions that assumed xloc was ordered

**Comment by ZoltanRacz** [comment]
In the end this was solved by including xlocstarts in EstimationResults
